redmine_fundation_plugin/config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
get 'fund_role_configs', :to => 'fund_role_configs#index'

get 'fund_role_configs(/:action(/:id))', controller: :fund_role_configs
post 'fund_role_configs(/:action(/:id))', controller: :fund_role_configs
patch 'fund_role_configs(/:action(/:id))', controller: :fund_role_configs
put 'fund_role_configs(/:action(/:id))', controller: :fund_role_configs


get 'fund_factor_configs', :to => 'fund_factor_configs#index'

get 'fund_factor_configs(/:action(/:id))', controller: :fund_factor_configs
post 'fund_factor_configs(/:action(/:id))', controller: :fund_factor_configs
patch 'fund_factor_configs(/:action(/:id))', controller: :fund_factor_configs
put 'fund_factor_configs(/:action(/:id))', controller: :fund_factor_configs

resources :funds, :only => [:index, :edit, :update]

get 'fund/frozen', :to => 'funds#frozen', :as => 'frozen'
get 'fund/unfrozen', :to => 'funds#unfrozen', :as => 'unfrozen'
get 'fund/update_frozen/:id', :to => 'funds#update_frozen'

redmine_fundation_plugin/app/controllers/funds_controller.rb
class FundsController < ApplicationController  

	before_action :check_partner
	before_action :check_owner, :only => [:edit, :update, :update_frozen]

	#Display pie and list all fund time logs.
	def index
		@factor = FundFactorConfig.find(1)
		entries = TimeEntry.find_by_sql("SELECT * FROM time_entries WHERE fund_total>0 AND fund_is_frozen=1 ORDER BY created_on")
		@total = 0
		@total_money = 0
		@shareholders = {}
		entries.each do |entry|
			name = entry.user.firstname
			if @shareholders.has_key?(entry.user.id)
				@shareholders[entry.user.id][:fund] += entry.fund_total || 0
				@shareholders[entry.user.id][:money] += entry.fund_money || 0
				@shareholders[entry.user.id][:resource] += entry.fund_resource || 0
				@shareholders[entry.user.id][:work] += entry.fund_work || 0
				@shareholders[entry.user.id][:money_fund] += (entry.fund_money || 0)*entry.fund_money_factor
				@shareholders[entry.user.id][:resource_fund] += (entry.fund_resource || 0)*entry.fund_resource_factor
				@shareholders[entry.user.id][:work_fund] += (entry.fund_work || 0)*entry.fund_work_factor
			else
				@shareholders[entry.user.id] = {
					:name => name,
					:fund => entry.fund_total || 0,
					:money => entry.fund_money || 0,
					:resource => entry.fund_resource || 0,
					:work => entry.fund_work || 0,
					:money_fund => (entry.fund_money || 0)*entry.fund_money_factor,
					:resource_fund => (entry.fund_resource || 0)*entry.fund_resource_factor,
					:work_fund => (entry.fund_work || 0)*entry.fund_work_factor
				}
			end
			@total += entry.fund_total if entry.fund_total
			@total_money += entry.fund_money if entry.fund_money
		end
	end

	def unfrozen
		@entries = TimeEntry.find_by_sql("SELECT * FROM time_entries WHERE fund_total>0 AND (fund_is_frozen IS NULL OR fund_is_frozen=0) ORDER BY created_on")
	end

	def frozen
		@entries = TimeEntry.find_by_sql("SELECT * FROM time_entries WHERE fund_total>0 AND fund_is_frozen=1 ORDER BY created_on")
	end

	def edit
    end

    def update
	    if @time_entry.update(time_entry_params)
	        respond_to do |format|
		        format.html {
		          flash[:notice] = l(:notice_successful_update)
		          redirect_back_or_default fund_path()
		        }
		        format.api  { render_api_ok }
      		end
	    else
	    	respond_to do |format|
		        format.html { render :action => 'edit' }
		        format.api  { render_validation_errors(@time_entry) }
	    	end
		end
    end

    def update_frozen
	    if @time_entry.update({:fund_is_frozen => params[:frozen]})
	        respond_to do |format|
		        format.html {
		          flash[:notice] = l(:notice_successful_update)
		          redirect_back_or_default params[:url]
		        }
		        format.api  { render_api_ok }
      		end
	    else
	    	respond_to do |format|
		        format.html { render :action => 'edit' }
		        format.api  { render_validation_errors(@time_entry) }
	    	end
		end
    end

	private
		def time_entry_params
	    	params.require(:time_entry).permit(:spent_on, :hours, :comments, :fund_work_role, :fund_work_role_monthly_salary, :fund_work, :fund_money, :fund_resource, :fund_work_factor, :fund_money_factor, :fund_resource_factor, :fund_total)
	    end
	    
		def check_partner
			is_partner = false
		    User.current.groups.each do |g|
		      puts g.lastname
		      if g.lastname == 'Partner'
		        is_partner = true
		      end
		    end

		    if !is_partner
		      render_403
		      return
		    end
		end

		def check_owner
			@time_entry = TimeEntry.find(params[:id])
			current_user = find_current_user
		    if User.current.id != @time_entry.user_id && !current_user.admin?
		    	render_403
	      		return
	      	end
		end
end

redmine_fundation_plugin/app/helpers/fund_helper.rb
module FundHelper


end

redmine_fundation_plugin/app/views/funds/_form.html.erb
<%= error_messages_for 'time_entry' %>
<%= back_url_hidden_field_tag %>

<div class="box tabular">
  <p><%= f.date_field :spent_on, :size => 10, :required => true %><%= calendar_for('time_entry_spent_on') %></p>
  <p><%= f.hours_field :hours, :size => 6, :required => true, :onchange => "onFundWorkChanged();" %></p>
  <p><%= f.text_field :comments, :size => 100, :maxlength => 1024, :required => Setting.timelog_required_fields.include?('comments') %></p>

  <%= call_hook(:view_timelog_edit_form_bottom, { :time_entry => @time_entry, :form => f }) %>

  <!-- Partner Fundation Form -->
  <input id='fund_role_configs' type='hidden' disabled="disabled" name='fund_role_configs' value='<%= FundRoleConfig.all.to_json %>'/>

  <hr />
  <p>
    <%= f.select :fund_work_role, FundRoleConfig.all.collect{|r| [r.name, r.name]}, {:include_blank => true, :required => false}, {:onchange => "onFundRoleChanged();" }
    %>
  </p>
  <p>
    <%= f.text_field :fund_work_role_monthly_salary, :size => 8, :readonly => true, :required => false %>
  </p>
  <p>工作时薪=月薪/22/8*工作小时</p>
  <p>
    <%= f.hours_field :fund_work, :size => 8, :required => false, :readonly => true %>
    <span>
      <%= l(:field_work_factor) %>:<%= @time_entry.fund_work_factor %>
    <span>
  </p>
  <p>
    <%= f.text_field :fund_money, :size => 8, :required => false, :onchange => "onFundChanged();" %>
    <span>
      <%= l(:field_money_factor) %>:<%= @time_entry.fund_money_factor %>
    </span>
  </p>
  <p>
    <%= f.text_field :fund_resource, :size => 8, :required => false, :onchange => "onFundChanged();" %>
    <span>
      <%= l(:field_resource_factor) %>:<%= @time_entry.fund_resource_factor %>
    </span>
  </p>
  <div style='display:none;'>
    <%= f.text_field :fund_work_factor %>
    <%= f.text_field :fund_money_factor %>
    <%= f.text_field :fund_resource_factor %>
  </div>

  <hr />
  
  <p>
    <%= f.hours_field :fund_total, :size => 8, :required => false, :readonly => true %>
    <span>
      <%= l(:field_fund_money) %>*<%= l(:field_money_factor) %>+<%= l(:field_fund_resource) %>*<%= l(:field_resource_factor) %>+<%= l(:field_fund_work) %>*<%= l(:field_work_factor) %>
    <span>
  </p>

</div>

<%= javascript_tag do %>
  function onFundWorkChanged(){
    var salary = parseInt($('#time_entry_fund_work_role_monthly_salary').val()) || 0;
    var hours = parseFloat($('#time_entry_hours').val()) || 0;
    $('#time_entry_fund_work').val(salary/22/8*hours);
    onFundChanged();
  }

  function onFundChanged(){
    var work_factor = parseFloat($('#time_entry_fund_work_factor').val());
    var money_factor = parseFloat($('#time_entry_fund_money_factor').val());
    var resource_factor = parseFloat($('#time_entry_fund_resource_factor').val());

    var money = parseInt($('#time_entry_fund_money').val()) || 0;
    var resource = parseInt($('#time_entry_fund_resource').val()) || 0;
    var work = parseInt($('#time_entry_fund_work').val()) || 0;
    $('#time_entry_fund_total').val(money*money_factor+resource*resource_factor+work*work_factor);
  }

  function onFundRoleChanged(){
    var role = $('#time_entry_fund_work_role').val();
    var fund_role_configs = JSON.parse($('#fund_role_configs').val());
    var salary = '';
    for(i=0;i<fund_role_configs.length;i++){
      if(fund_role_configs[i].name==role){
        salary = fund_role_configs[i].monthly_salary;
        break;
      }
    }
    $('#time_entry_fund_work_role_monthly_salary').val(salary);
    onFundWorkChanged();
  }

  $(document).ready(function(){
  });

<% end %>

redmine_fundation_plugin/app/views/funds/_list.html.erb
<div class="autoscroll">
<table class="list odd-even time-entries">
<thead>
  <tr>
    <th rowspan="2"><%=l(:field_spent_on)%></th>
    <th rowspan="2"><%=l(:label_user)%></th>
    <th rowspan="2"><%=l(:label_issue)%></th>
    <th rowspan="2"><%=l(:label_fund)%></th>
    <th rowspan="2"><%=l(:label_investment)%></th>
    <th rowspan="2"><%=l(:label_receivables)%></th>
    <th colspan="3"><%=l(:label_constitution)%></th>
    <th rowspan="2"><%=l(:field_comments)%></th>
    <th rowspan="2"></th>
  </tr>
  <tr>
    <th><%=l(:label_money)%></th>
    <th><%=l(:label_work)%></th>
    <th><%=l(:label_resource)%></th>
  </tr>
</thead>
<tbody>
  <% entries.each do |entry|%>
  <tr id="time-entry-<%= entry.id %>" class="time-entry <%= cycle("odd", "even") %>">
    <td><%= "#{format_date(entry.spent_on)}" %></td>
    <td><%= "#{entry.user.firstname}"%></td>
    <td class="fund_left_align"><%= entry.issue.subject if entry.issue %></td>
    <td><%= entry.fund_total %></td>
    <td><%= (entry.fund_money||0)+(entry.fund_work||0)+(entry.fund_resource||0) %></td>
    <td><%= entry.fund_total - (entry.fund_money||0) - (entry.fund_work||0) - (entry.fund_resource||0) %></td>
    <td class="fund_right_align"><%= "#{format("%.2f*%d=%.2f", entry.fund_money_factor, entry.fund_money || 0, entry.fund_money_factor * (entry.fund_money || 0)) }" %></td>
    <td class="fund_right_align"><%= "#{format("%.2f*%d=%.2f", entry.fund_work_factor, entry.fund_work || 0, entry.fund_work_factor * (entry.fund_work || 0)) }" %></td>
    <td class="fund_right_align"><%= "#{format("%.2f*%d=%.2f", entry.fund_resource_factor, entry.fund_resource || 0, entry.fund_resource_factor * (entry.fund_resource || 0)) }" %></td>
    <td class="fund_left_align"><%= entry.comments %></td>
    <td>
      <% if is_frozen %>
        <%= link_to l(:button_unfrozen), { controller: "funds", action: "update_frozen", id: entry.id, frozen: false, url: frozen_path() } %>
      <% else %>
        <%= link_to l(:button_frozen), { controller: "funds", action: "update_frozen", id: entry.id, frozen: true, url: unfrozen_path() } %>
        <%= link_to l(:button_edit), edit_fund_path(entry),
            :title => l(:button_edit),
            :class => 'icon-only icon-edit' %>
        <%= link_to l(:button_delete), time_entry_path(entry),
            :data => {:confirm => l(:text_are_you_sure)},
            :method => :delete,
            :title => l(:button_delete),
            :class => 'icon-only icon-del' %>
      <% end %>
    </td>
  </tr>
  <% end %>
</tbody>
</table>
</div>

redmine_fundation_plugin/app/views/funds/_nav_tab.html.erb
<% content_for :header_tags do %>
	<%= stylesheet_link_tag 'fund_config.css', :plugin => 'redmine_fundation_plugin' %>
<% end %>

<div id="fund-setting-nav-menu">
	<ul>
		<li style='<%= params[:action] == "index" ? 'background-color:#d4e3f7;':'' %>'>
			<%= link_to l(:label_fundation_home), funds_path %>
		</li>
		<li style='<%= params[:action] == "frozen" ? 'background-color:#d4e3f7;':'' %>'>
			<%= link_to l(:label_fundation_frozen), frozen_path %>
		</li>
		<li style='<%= params[:action] == "unfrozen" ? 'background-color:#d4e3f7;':'' %>'>
			<%= link_to l(:label_fundation_unfrozen), unfrozen_path %>
		</li>
	</ul>
</div>

redmine_fundation_plugin/app/views/funds/_pies.html.erb
<div class="pie_list">
	<% pies.each do |v| %>
		<div class="pie" data-percent="<%= v[:value].to_f/total.to_f*100 %>" data-scale-color="#ffb400">
			<div class="label">
				<p><%= v[:name] %></p>
				<p><%= "#{format("%.2f", v[:value].to_f/total.to_f*100, 2)}%" %></p>
				<p><%= "#{format("%.2f", v[:value].to_f)}" %></p>
			</div>
		</div>
	<% end %>
	<div style="clear:both;">
</div>

redmine_fundation_plugin/app/views/funds/edit.html.erb
<h2><%= l(:label_spent_time) %></h2>

<%= labelled_form_for @time_entry, :url => fund_path(@time_entry), :html => {:multipart => true} do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <%= submit_tag l(:button_save) %>
<% end %>

redmine_fundation_plugin/app/views/funds/frozen.html.erb
<% content_for :header_tags do %>
	<%= stylesheet_link_tag 'index.css', :plugin => 'redmine_fundation_plugin' %>
<% end %>

<%= render :partial => 'nav_tab' %>


<% if @entries.empty? %>
	<p class="nodata"><%= l(:label_no_data) %></p>
<% else %>
	<%= render :partial => 'list', :locals => { 
		:is_frozen => true, 
		:entries => @entries 
		}
	%>
<% end %>

<% html_title(l(:label_fundation_frozen)) %>

redmine_fundation_plugin/app/views/funds/index.html.erb
<% content_for :header_tags do %>
	<%= stylesheet_link_tag 'index.css', :plugin => 'redmine_fundation_plugin' %>
<% end %>

<%= javascript_include_tag 'jquery.easypiechart.min', :plugin => 'redmine_fundation_plugin' %>

<%= render :partial => 'nav_tab' %>

<h2><%= l(:label_total_fundation) %>:<%= "#{format("%.2f", @total)}" %></h2>
<h3><%= l(:label_current_risk_factor_config) %></h3>
<ul class="risk_factor_config">
	<li><%=l(:label_money)+l(:fund_factor)%>:<%= "#{format("%.2f", @factor.money_factor)}" %></li>
	<li><%=l(:label_resource)+l(:fund_factor)%>:<%= "#{format("%.2f", @factor.resource_factor)}" %></li>
	<li><%=l(:label_work)+l(:fund_factor)%>:<%= "#{format("%.2f", @factor.work_factor)}" %></li>
</ul>

<div class="autoscroll">
<table class="list odd-even time-entries">
<thead>
  <tr>
    <th><%=l(:label_user)%></th>
    <th><%=l(:label_fund)%></th>
    <th><%=l(:label_money)%></th>
    <th><%=l(:label_resource)%></th>
    <th><%=l(:label_work)%></th>
  </tr>
</thead>
<tbody>
<% @shareholders.each do |k,v| %>
	<tr id="user-<%= k %>" class="<%= cycle("odd", "even") %>">
		<td><%= v[:name] %></td>
		<td><%= "#{format("%.2f", v[:fund])}" %></td>
		<td><%= "#{format("%.2f", v[:money_fund])}" %></td>
		<td><%= "#{format("%.2f", v[:resource_fund])}" %></td>
		<td><%= "#{format("%.2f", v[:work_fund])}" %></td>
	</tr>
<% end%>
</tbody>
</table>

<% unless @shareholders.empty? %>
  <%= render 	:partial => 'pies', 
  				:locals => {
				  	:total => @total,
				  	:pies => @shareholders.map do |k,v|
				  		{
				  			:name => v[:name],
				  			:value => v[:fund]
				  		}
				  	end
  				}
  %>
<% end %>

<hr/>

<h2><%= l(:label_investment) %>:<%= l(:label_no_risk) %></h2>

<div class="autoscroll">
<table class="list odd-even time-entries">
<thead>
  <tr>
    <th><%=l(:label_user)%></th>
    <th><%=l(:label_money)%></th>
    <th><%=l(:label_resource)%></th>
    <th><%=l(:label_work)%></th>
  </tr>
</thead>
<tbody>
<% @shareholders.each do |k,v| %>
	<tr id="user-<%= k %>" class="<%= cycle("odd", "even") %>">
		<td><%= v[:name] %></td>
		<td><%= "#{format("%.2f", v[:money])}" %></td>
		<td><%= "#{format("%.2f", v[:resource])}" %></td>
		<td><%= "#{format("%.2f", v[:work])}" %></td>
	</tr>
<% end%>
</tbody>
</table>

<h3><%= l(:label_total_money) %>:<%= "#{format("%.2f", @total_money)}" %></h3>

<% unless @shareholders.empty? %>
  <%= render 	:partial => 'pies', 
  				:locals => {
				  	:total => @total_money,
				  	:pies => @shareholders.to_a.map do |k,v|
				  		{
				  			:name => v[:name],
				  			:value => v[:money]
				  		}
				  	end
  				}
  %>
<% end %>

<% html_title(l(:label_fundation_home)) %>

<%= javascript_tag do %>
    $(function() {
        $('.pie').easyPieChart({
        });
    });
<% end %>

redmine_fundation_plugin/app/views/funds/unfrozen.html.erb
<% content_for :header_tags do %>
	<%= stylesheet_link_tag 'index.css', :plugin => 'redmine_fundation_plugin' %>
<% end %>

<%= render :partial => 'nav_tab' %>

<% if @entries.empty? %>
	<p class="nodata"><%= l(:label_no_data) %></p>
<% else %>
	<%= render :partial => 'list', :locals => { 
		:is_frozen => false, 
		:entries => @entries 
		}
	%>
<% end %>

<% html_title(l(:label_fundation_unfrozen)) %>